language: php
php:
  - 7.0
before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_8.x" | sudo -E bash -
  - sudo apt-get install -y wput
script:
  - npm install
  - composer install
  - npm run build
after_success:
  - npm run upload
