language: node_js
node_js:
  - 8
before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -y update
  - sudo apt-get -y install php7.1
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
script:
  - composer install
  - node ./build/generateHashes
after_success:
  - find ./*.{js,php,css,png,htaccess} -type f -exec curl -3 --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/nielsgerritsen/cryptoeuro/ \;
  - find ./**/*.{php} -type f -exec curl -3 --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/nielsgerritsen/cryptoeuro/ \;
  - find ./vendor/** -type f -exec curl -3 --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/nielsgerritsen/cryptoeuro/vendor/ \;
